### ISSUE TITLE
haproxy_statusCode not correctly pared

### ISSUE THREAD

**Issue by WRTHacker** [hariom282538/graylog-content-pack-haproxy-json#1]
Hi, install went well, many thanks, but the haproxy_statusCode from the following line is not parsed sucessfully:

funk haproxy[26784]: {haproxy_clientIP:193.174.118.209,haproxy_clientPort:51222,haproxy_dateTime:27/Nov/2018:21:44:43.568,haproxy_frontendNameTransport:fe_whs_mail~,haproxy_backend:be_WebMail,haproxy_serverName:mail.koellers.net,haproxy_Tw:0,haproxy_Tc:5,haproxy_Tt:444,haproxy_bytesRead:1425,haproxy_terminationState:--,haproxy_actconn:1,haproxy_FrontendCurrentConn:1,haproxy_backendCurrentConn:0,haproxy_serverConcurrentConn:0,haproxy_retries:0,haproxy_srvQueue:0,haproxy_backendQueue:0,haproxy_backendSourceIP:192.168.10.1,haproxy_backendSourcePort:60200,haproxy_statusCode:404,haproxy_serverIP:192.168.1.40,haproxy_serverPort:443,haproxy_frontendIP:94.79.171.94,haproxy_frontendPort:443,haproxy_capturedRequestHeaders:{mail.koellers.net},haproxy_httpRequest:GET /sdfsdfsdfs/erwer HTTP/1.1}

The "Manage Stream Rules" states:

Field haproxy_statusCode must be greater than 399
Field haproxy_statusCode must be smaller than 500

No Idea what's wrong here.

**Comment by hariom282538** [comment]
> Hi, install went well, many thanks, but the haproxy_statusCode from the following line is not parsed sucessfully:
> 
> funk haproxy[26784]: {haproxy_clientIP:193.174.118.209,haproxy_clientPort:51222,haproxy_dateTime:27/Nov/2018:21:44:43.568,haproxy_frontendNameTransport:fe_whs_mail~,haproxy_backend:be_WebMail,haproxy_serverName:mail.koellers.net,haproxy_Tw:0,haproxy_Tc:5,haproxy_Tt:444,haproxy_bytesRead:1425,haproxy_terminationState:--,haproxy_actconn:1,haproxy_FrontendCurrentConn:1,haproxy_backendCurrentConn:0,haproxy_serverConcurrentConn:0,haproxy_retries:0,haproxy_srvQueue:0,haproxy_backendQueue:0,haproxy_backendSourceIP:192.168.10.1,haproxy_backendSourcePort:60200,haproxy_statusCode:404,haproxy_serverIP:192.168.1.40,haproxy_serverPort:443,haproxy_frontendIP:94.79.171.94,haproxy_frontendPort:443,haproxy_capturedRequestHeaders:{mail.koellers.net},haproxy_httpRequest:GET /sdfsdfsdfs/erwer HTTP/1.1}
> 
> The "Manage Stream Rules" states:
> 
> Field haproxy_statusCode must be greater than 399
> Field haproxy_statusCode must be smaller than 500
> 
> No Idea what's wrong here.

@WRTHacker Thanks for writing and sharing this use-case. Although, as I said and mentioned on the content-pack doc, I used haproxy 1.5 version while development and testing. So, content-pack is compatible with that version. As I just checked haproxy upgraded its version and by default latest version will be installed but there is a way around (sudo apt-get install haproxy=1.5.19-2ppa1~xenial)  <-- use this command to install haproxy 1.5.

**Comment by hariom282538** [comment]
@WRTHacker closing this issue. Please share/report any new issue related to this project.
