### ISSUE TITLE
compatible with graylog version 3 or higher

### ISSUE THREAD

**Issue by AminAshtiani** [hariom282538/graylog-content-pack-haproxy-json#2]
I want to install this content pack on graylog version v3.0.2 but I did not goes well, I want to know that it is compatible with version 3.0.2 or not?

**Comment by hariom282538** [comment]
I haven't checked this content pack with new graylog (i.e 3.X) Please share more info (like what kind of error you're getting in graylog running logs) I'll try to make this CP compatible if i have info.

**Comment by pasechnik2307** [comment]
I also can't install this CP with Graylog v3.1.2, update it please!

**Comment by hariom282538** [comment]
> I also can't install this CP with Graylog v3.1.2, update it please!

Noted.

**Comment by vjcalel** [comment]
when can we expect an update to work with graylog-3 ?

**Comment by hariom282538** [comment]
@vjcalel  @AminAshtiani  @pasechnik2307 Upgraded - Refer Master branch for the latest Graylog 3.X and HaProxy 1.8 Content Pack. For old graylog2 content pack refer graylog2_contentPack branch.
